language: node_js
node_js:
- '7'
cache: yarn
script: node_modules/.bin/react-scripts test --env=jsdom --coverage --watchAll
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
env:
  global:
    secure: JCkQJ1LCMbzAte9NcVPVkp+6UHM0v4ELJUsGP8P//uZvMMqthXmlgprqCyVazR1yYsUYHqEqeRUuoEggUYNlc+aQZrZ9Wqbm3/fbHRrepTzebfn+ZQABsOeGqLVwowoJfBPLbTBVtsghE6GzbB/sXoPCMvO/fpdqxcgAWHpHuI8qHhPNCK7fllgQ9P2YFmON+INuxg+lKYZu6QbjBlTSG34qMGP0GsZp2z9gG4CXuCT7un9YGQlScxXiVDyspQ1IqHqZ1WdBJFz5gibCzSQifHhtKbFU5i5vyjJPwhMwBrefTzCncahdlc75E26GgLx8AyHd+MBFAqXsiDIY3mK9eVrxw1emCX7VlO7bHQNQv1BQN7wRdruBOBKTvPMtNuLLlCC499slp4d9XZILMyYLhqqPdul12bMIe7wXGzhVaLpfMQE6Jwy6n3LA/4lag+U/sZu1JzPNkF/KsPp78Gn1fxxCL748r98dAAgOamShiZFKnk7RHa4Wszu9axIlzpWzKVikBi/mCh09Nmp+k2rSeTn11iePwa9QWTMZZ2Xht7WmauCJ05a4nevpfuZAVPW1wEhkJeH1AwyH1Dicc1eIxmZNae9GnoCI/PQg5zCPxJgL+17+n3T2fjMe13EUrogUrJGX8nO/BcQgcIaEhhhdhzSr+369a9ZmWGm3NrG4JwA=
