// flow-typed signature: 9de3b10ae448bbf56b55db5f26872410
// flow-typed version: <<STUB>>/mockdate_v2.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mockdate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mockdate' {
  declare function set(
    date: string | number | Object,
    timeOffset: ?number
  ): void;
  declare function reset(): void;

  declare module.exports: {
    set: typeof set,
    reset: typeof reset,
  };
}
