// flow-typed signature: 53ed67f5266c84b30b65b189a3384e04
// flow-typed version: <<STUB>>/react-cellblock_v^2.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cellblock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

type ReactCellblockColumnDefaultProps = {
  className: string,
  width: string,
}

type ReactCellblockColumnProps = {
  className?: string,
  width?: string,
}

declare module 'react-cellblock' {
  declare class Row extends React$Component {
    props: {|
      className?: string,
    |};
  }
  declare class Column extends React$Component {
    props: {|
      className?: string,
      width?: string,
    |};
  }
  declare class Grid extends React$Component {
    props: {||};
  }
}
